[package]
name = "macros"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro-crate = "3.3.0"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"
